networks:
  default:
    name: roboshop
    driver: bridge
services:
  mongodb:
    image: visweshbonam/mongodb:v1
    container_name: mongodb

  catalogue:
    image: visweshbonam/catalogue:v1
    container_name: catalogue
    depends_on: 
      - mongodb

  redis:
    image: redis:7.0
    container_name: redis
  
  user:
    image: visweshbonam/user:v1
    container_name: user
    depends_on:
      - redis
      - mongodb

  cart:
    image: visweshbonam/cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue
    

  mysql:
    image: visweshbonam/mysql:v1
    container_name: mysql
    
  shipping:
    image: visweshbonam/shipping:v1
    container_name: shipping
    depends_on:
      - cart
      - mysql
  
  rabbitmq:
    image: visweshbonam/rabbitmq:v1
    container_name: rabbitmq
  
  payment:
    image: visweshbonam/payment:v1
    container_name: payment
    depends_on:
      - cart
      - user
      - rabbitmq

  frontend:
    image: visweshbonam/frontend:v1
    container_name: frontend
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
    ports:
      - "80:80"
  

    